name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  arm64v8:
    if: false # disable arm64v8 cross compile for now

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - uses: docker/build-push-action@v4
      with:
        push: false
        build-args: |-
          ARCH=arm64v8
          ALPINE_VERSION=3.18.2
        file: Containerfile
        tags: amd64/krakatoa:latest

  amd64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/build-push-action@v4
      with:
        push: false
        build-args: |-
          ARCH=amd64
          ALPINE_VERSION=3.18.2
        file: Containerfile
        tags: amd64/krakatoa:latest

